// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCepyMECIR91mVJOfcI9YsQvs-LRQB0zN0',
    appId: '1:115505381722:web:ddc7dedfe4d64e48dbf363',
    messagingSenderId: '115505381722',
    projectId: 'erp-simples-pic',
    authDomain: 'erp-simples-pic.firebaseapp.com',
    storageBucket: 'erp-simples-pic.firebasestorage.app',
    measurementId: 'G-KS253M3Y8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6t2eOCnRkh-oJ5yc8fj6KdxJDo27Po8',
    appId: '1:115505381722:android:8fe9d76ecc5a7dcedbf363',
    messagingSenderId: '115505381722',
    projectId: 'erp-simples-pic',
    storageBucket: 'erp-simples-pic.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCepyMECIR91mVJOfcI9YsQvs-LRQB0zN0',
    appId: '1:115505381722:web:946873055157d7e0dbf363',
    messagingSenderId: '115505381722',
    projectId: 'erp-simples-pic',
    authDomain: 'erp-simples-pic.firebaseapp.com',
    storageBucket: 'erp-simples-pic.firebasestorage.app',
    measurementId: 'G-TPZ56NNYM3',
  );
}
